### ISSUE TITLE
redis 3.0: Exists command is variadic

### ISSUE THREAD

**Issue by etaty** [etaty/rediscala#104]
http://redis.io/commands/exists

**Comment by gchudnov** [comment]
@etaty 
just wanted to make a PR that implements variadic [exists](https://redis.io/commands/exists).
Guess that must me a command with a different name, like `existsMany`, what do you think?

Otherwise the public API will be broken, since `exists` returns `Boolean` and the variadic version returns `Long`.

**Comment by etaty** [comment]
Yes, `existMany` is good
thanks
