### ISSUE TITLE
Do you have a sample how to use RedisClientPool ?

### ISSUE THREAD

**Issue by lahirug** [etaty/rediscala#85]
I couldn't find one, if you have some sample it would be great. I would like to contribute with a proper sample to your demo project.

**Comment by etaty** [comment]
Nope, there is no sample, feel free to contribute :+1: . 
You can do a demo with the docs in the `readme` and the `test`

**Comment by lahirug** [comment]
Hi Valerian,

I want to  store these objects to redis and get them back. What should be
the easiest approach to do that. We are currently using Json parsing to
convert the object to string and parse back to the object.

TimeseriesValues(complete: Boolean, t: Array[Long], x: Array[Long], y:
Array[Long])

case class TimeseriesDefinitions(complete: Boolean, counters:
Map[String, Set[String]])


case class TraceLogResults(complete: Boolean, log: String)

**Comment by etaty** [comment]
Depends of how you query them back.
There are structure for storing object or list in redis.
Otherwise if you want serialization json is great because you can debug, otherwise you can try Kryo
https://github.com/EsotericSoftware/kryo#scala
Or scala pickling
https://github.com/scala/pickling

But unless you have performance issues, json is ok (be careful of which json serializer you use)

**Comment by lahirug** [comment]
Valerian,

All good now and it just worked ! Fully removed old redis-client and
replaced with rediscala.

Ty
